# Generated by Django 3.2 on 2021-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210516_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, choices=[('مهندس موقع', 'مهندس موقع'), ('محاسب موقع', 'محاسب موقع'), ('مدير مشروعات', 'مدير مشروعات'), ('رئيس مجلس ادراه', 'رئيس مجلس ادراه')], max_length=100, null=True),
        ),
    ]
