# Generated by Django 3.2 on 2021-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='project_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
