# Generated by Django 3.2 on 2021-06-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_site_project_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
