# Generated by Django 3.2 on 2021-05-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_avatar'),
        ('acc', '0003_auto_20210506_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_status', models.CharField(choices=[('ايداع', 'ايداع'), ('سحب', 'سحب')], max_length=100)),
                ('operation_name', models.CharField(max_length=100)),
                ('operation_amount', models.IntegerField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_name',
        ),
        migrations.DeleteModel(
            name='Safety',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
