# Generated by Django 3.2 on 2021-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_operation_operations_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operations_document',
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_document',
            field=models.ImageField(blank=True, null=True, upload_to='operation_documents/'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_status',
            field=models.CharField(blank=True, choices=[('ايداع', 'ايداع'), ('سحب', 'سحب')], max_length=100, null=True),
        ),
    ]
