# Generated by Django 3.2 on 2021-05-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_auto_20210512_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
