# Generated by Django 3.2 on 2021-05-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210516_2203'),
        ('acc', '0008_operation_operation_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.site'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operation_set', to='main.profile'),
        ),
    ]
