# Generated by Django 3.2 on 2021-05-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opertion_status', models.CharField(choices=[('paid', 'paid'), ('collected', 'collected')], max_length=100)),
                ('operation_name', models.CharField(max_length=100)),
                ('operation_amount', models.IntegerField()),
                ('safety_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eng.site')),
            ],
        ),
    ]
