# Generated by Django 3.2 on 2021-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safety',
            name='opertion_status',
            field=models.CharField(choices=[('ايداع', 'ايداع'), ('سحب', 'سحب')], max_length=100),
        ),
    ]
